---
# playbooks/site.yml
# playbook to run all playbooks in the correct order

- name: Include bootstrap playbook
  ansible.builtin.import_playbook: bootstrap.yml

- name: Include base playbook
  ansible.builtin.import_playbook: base.yml
