[all]
lab ansible_host=192.168.0.101 alias=lab

[all:vars]
ansible_user=ansible
ansible_become=true
ansible_python_interpreter=/usr/bin/python3

[bootstrap]
lab

[bootstrap:vars]
bootstrap_login_user=admin
